
export const ALL_FEATURES = [
    {
        key: 'dashboard-basic',
        name: 'Acompanhamento',
        description: 'Acesso à visualização de Acompanhamento.',
        href: '/dashboard',
        icon: 'BarChart3',
    },
    {
        key: 'works-management',
        name: 'Obras',
        description: 'Permite criar e gerenciar obras/projetos.',
        href: '/dashboard/obras',
        icon: 'HardHat',
    },
    {
        key: 'financial-view',
        name: 'Financeiro',
        description: 'Acesso ao módulo Financeiro.',
        href: '',
        icon: 'Wallet',
    },
    {
        key: 'financial-dashboard',
        name: 'Painel Geral',
        description: 'Visualização geral das finanças.',
        href: '/dashboard/financeiro/painel',
        icon: 'LayoutDashboard',
        parentKey: 'financial-view',
    },
    {
        key: 'accounts-payable',
        name: 'Contas a Pagar',
        description: 'Gerenciamento de contas a pagar.',
        href: '/dashboard/financeiro/contas-a-pagar',
        icon: 'TrendingDown',
        parentKey: 'financial-view',
    },
    {
        key: 'accounts-receivable',
        name: 'Contas a Receber',
        description: 'Gerenciamento de contas a receber.',
        href: '/dashboard/financeiro/contas-a-receber',
        icon: 'TrendingUp',
        parentKey: 'financial-view',
    },
    {
        key: 'cash-flow',
        name: 'Fluxo de Caixa',
        description: 'Projeção do fluxo de caixa.',
        href: '/dashboard/financeiro/fluxo-de-caixa',
        icon: 'AreaChart',
        parentKey: 'financial-view',
    },
    {
        key: 'fiscal-documents',
        name: 'Documentos',
        description: 'Repositório e emissão de documentos fiscais.',
        href: '/dashboard/financeiro/documentos',
        icon: 'FileText',
        parentKey: 'financial-view',
    },
    {
        key: 'user-management',
        name: 'Usuários',
        description: 'Permite gerenciar os usuários da empresa.',
        href: '/dashboard/users',
        icon: 'Users',
    },
    {
        key: 'inventory-management',
        name: 'Estoque',
        description: 'Acesso ao controle de estoque.',
        href: '/dashboard/estoque',
        icon: 'Warehouse',
    },
    {
        key: 'advanced-reporting',
        name: 'Relatórios',
        description: 'Permite a exportação de relatórios detalhados.',
        href: '/dashboard/relatorios',
        icon: 'FileText',
    }
];

export const DEFAULT_FEATURE_KEYS = [
    'dashboard-basic',
    'works-management',
    'financial-view',
    'financial-dashboard',
    'accounts-payable',
    'accounts-receivable',
    'cash-flow',
    'fiscal-documents',
    'user-management',
    'inventory-management',
];
