services:
  db:
    image: postgres:15-alpine
    container_name: constructioncon-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=constructioncon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
